### ISSUE TITLE
Update button in Calculations

### ISSUE THREAD

**Issue by jepke** [TurtIeSocks/Koji#112]
Havent really found what is causing it but sometimes i have to refresh in order to use the Update button for route calculations again as it stays `purpled out`.

**Comment by jepke** [comment]
@TurtIeSocks did something change over the last month ? just tried to reproduce it but im unable at this point.

**Comment by TurtIeSocks** [comment]
I'm not sure, but I'll go ahead and close for now. If it happens again feel free to reopen.
