### ISSUE TITLE
Non Unique names

### ISSUE THREAD

**Issue by jepke** [TurtIeSocks/Koji#135]
This is more of a problem on bigger installs where you loose track of what you actually have in your DB. Currently Koji allows you to save routes with duplicate names. ~~Cant find anything in the API that calls routes by name but maybe.~~
Projects are called for by name so this might become a problem.

Force unique on the name column in the DB might be a bit too much but maybe it can be handled from the cache.

**Comment by TurtIeSocks** [comment]
There's a couple of reasons why routes are allowed to have duplicate names. 

1. When you have `Save to Koji db` turned on when clustering from the client, it inherits the name of the polygon. So you'll end up with issues if you run the 3 categories back to back. 

2. Routes have a unique property, that is currently undocumented but on the list, that if they have a matching name as its associated geofence, when the geofence name is changed, the route names are updated to match. 

I experimented with adding _CP or _CR (whatever the acronym of the route mode is) but it ended up being a mess. I worked through several different scenarios over multiple days but eventually decided that this was the best balance for working with RDM and Flygon. 

Once I fix the rdm connection the reasoning may become clearer. Maybe.

**Comment by jepke** [comment]
Kinda prepping for the moment the RDM update will work but cant currently think of a neat way to organize a ton of fences and a bunch of routes.

Maybe with Flygon i dont need routes anymore and just tell Flygon what and how i want routes and have Flygon and Koji figure it out... Hoping 🙏

**Comment by TurtIeSocks** [comment]
I believe I added the description column for routes to help with this. I can't imagine needing more than 3, maybe 4 if you want to hold onto a bootstrap route, per fence though?

**Comment by TurtIeSocks** [comment]
On that note, I'm not against having a unique name-mode constraint. I think I left it off specifically for bootstrap routes but if we build this into flygon then there's no need to save one anyway.

**Comment by jepke** [comment]
I might just need to rethink my naming convention with this. Thing is poracle uses the fence names so i dont want to make it cryptic as stupid human users dont know what to pick then.

Might be trying to build rockets here but i think 2 name columns might do `system-naming` and `human-naming`
Eg:
Then i can make a naming convention {{ areaXX-fencename-function }} as organized system name to be used with othertools for configuration but human name would be just {{ Cityname }} and used for interfaces with human interaction or display.

**Comment by TurtIeSocks** [comment]
![image](https://user-images.githubusercontent.com/58572875/230213517-77563fb8-fbb9-4d3d-ac58-6a42b0b97805.png)
c&p from someone else I sent...docs coming soon.

Go to your properties tab and create a name property with the category set to string. The name property with category Database is assigned to every new area created by default, so you'll want to delete that if you want a custom name. 

The name/database property means that the name given in the sql column will be automatically/dynamically appended to the area whenever it's called through the API, assuming they're calling the format of either a Feature/Feature Collection/Poracle. 

However the name/string can be manually set to whatever you want. So if your area in Koji is called `Berlin_South`, you can call it `South` in this custom name property, which is what will be presented to RM/Poracle/users.

**Comment by TurtIeSocks** [comment]
We good with this @jepke ?

**Comment by jepke** [comment]
Yea ill close it i think i can come up with something with those properties
