### ISSUE TITLE
Import Wizard doesn't save name as property

### ISSUE THREAD

**Issue by kamieniarz** [TurtIeSocks/Koji#143]
I have imported geofence.json from poracle. Property name, eg. `"name": "london",` got saved as geofence's name but not as a database name property so in fact in api and in export geofences won't have a name

**Comment by TurtIeSocks** [comment]
I can't seem to replicate this. 

Have you deleted your `name`/`database` property?

Do you have a custom `name`/`string` property? 
^Shouldn't technically matter since this is the db query but asking anyway.
```rust
        let record = Entity::find()
            .filter(property::Column::Name.eq("name"))
            .filter(property::Column::Category.eq("database"))
            .one(db)
            .await?;
```

**Comment by TurtIeSocks** [comment]
Reread your comment and I guess you must be referring to a `name`/`string` property. I added a `name`/`string` prop to my koji and imported some fences from a poracle style json but it still saved them as a `name`/`database` property so I'm not sure what happened for you.

**Comment by TurtIeSocks** [comment]
Ideally #144 is replacing the need to have a custom name/string property anyway.
