### ISSUE TITLE
Ability to only show unknown or known spawnpoints.

### ISSUE THREAD

**Issue by jepke** [TurtIeSocks/Koji#149]
For unknowns it makes rendering faster on huge areas and somewhat slower databases. Makes creating TTH find routes faster

**Comment by TurtIeSocks** [comment]
This ability already exists for clustering/routing, but I believe is lacking when it comes to filtering the points on the map. Would be a really easy first PR to adapt the code from one place to another ;)

**Comment by jepke** [comment]
Lol you are really tricking me back in to coding.
