### ISSUE TITLE
Bootstrapping Bug / Problem

### ISSUE THREAD

**Issue by Jebula999** [TurtIeSocks/Koji#161]
Not sure how to explain this fully.
Was discussed in detail in a Discord channel, note that the same issue is present on RDMTools where this was originally discovered: https://discord.com/channels/456432530531549195/679354299897348097/1068233763064131734
Images below from that conversation/report:
![image](https://github.com/TurtIeSocks/Koji/assets/11380895/09f5b76a-72d2-45ad-84ff-f98f5964ccf8)
![image](https://github.com/TurtIeSocks/Koji/assets/11380895/737725dd-05db-4dcf-9763-b7fb679f77ea)

Basically, it seems that in certain parts of France (And potentially others) the S2 cells go a bit out of wack, and you end up with bootstraps that look like this:
![image](https://github.com/TurtIeSocks/Koji/assets/11380895/d8a86849-067c-450c-a77f-0778df9a982b)
![image](https://github.com/TurtIeSocks/Koji/assets/11380895/aef10c36-b091-44fc-91a4-6bcee216bcc6)

I've seen this problem in other countries, just cannot remember which ones.
It essentially makes it impossible to bootstrap parts of certain countries, and no clear way to see which areas are affected or the cause of the problem.
Not sure if the issue lies with the calculations of the S2 Cells, or the S2 Cells themselves.

Not sure what other info I can provide, but if you have any questions please give me a shout :)
- Jeb

**Comment by TurtIeSocks** [comment]
Damn... No one had complained about this, thought it wasn't a problem with koji and wasn't sure where to test. I can confirm this gets wonky in France, though with slightly different results. I'll do some more testing later.
