### ISSUE TITLE
[Feature Request] Ability to save route as GPX file

### ISSUE THREAD

**Issue by Jebula999** [TurtIeSocks/Koji#163]
Pretty much as the title says.
Along with all the format/text options to output, perhaps a button to export/download a GPX file.

**Comment by lenisko** [comment]
for what purpose?

**Comment by Fabio1988** [comment]
Only relevant for spoofer I guess, won't support it, we are mapper ;)

**Comment by lenisko** [comment]
Yeah, can't think about other use-case.

**Comment by Jebula999** [comment]
Yup, for making GPX routes for the spoofer community.
I love making them so was just a thought.

Understandable 👍

**Comment by TurtIeSocks** [comment]
A PR would be accepted but I have no intention of writing this myself.
