### ISSUE TITLE
Update for Rust 1.71 

### ISSUE THREAD

**Issue by wateredstorm** [TurtIeSocks/Koji#180]
In version 1.71 rust the package geo 0.24.0 fails with error:

error[E0275]: overflow evaluating the requirement `[closure@/home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/geo-0.24.0/src/algorithm/map_coords.rs:856:69: 856:72]: Fn<(geo_types::Coord<T>,)>`
  |
  = help: consider increasing the recursion limit by adding a `#![recursion_limit = "256"]` attribute to your crate (`geo`)
  = note: required for `&[closure@/home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/geo-0.24.0/src/algorithm/map_coords.rs:856:69: 856:72]` to implement `Fn<(geo_types::Coord<T>,)>`
  = note: 128 redundant requirements hidden
  = note: required for `&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&...` to implement `Fn<(geo_types::Coord<T>,)>`
  = note: the full type name has been written to '/home/ubuntu/Koji/server/target/release/deps/geo-4d16eba0bd21217f.long-type-4205409412743622008.txt'

**Comment by TurtIeSocks** [comment]
Resolved in #181
