### ISSUE TITLE
Options to find Geofences without a project assigned.

### ISSUE THREAD

**Issue by Cronick** [TurtIeSocks/Koji#186]
When importing and creating new geofences, it can sometime be a struggle to find the new geofences.

So an option to see geofences without a project assigned would help on this, as we can't currently save new geofences directly to a project.

Just like the option we have with "Mode" and the unset option.

![image](https://github.com/TurtIeSocks/Koji/assets/5100210/66c5597b-ea69-450e-a3a3-217533d79002)

**Comment by TurtIeSocks** [comment]
This is a good idea! Opened a PR for it.
