### ISSUE TITLE
Use "name" property when exporting to RDM

### ISSUE THREAD

**Issue by DrMurx** [TurtIeSocks/Koji#196]
Currently, it looks like Koji uses the name column of the geofence table when exporting an instance to RDM. It should rather use whatever the "name" property points to. This _may_ be the database name (which is the default), but it may be a dedicated name added as string property.

Reasoning: 
1. It would align with the export to ReactMap/Poracle which relies the name property
2. Given RDM's (questionable) design choice to use the instance name as primary key and any foreign key relation within the database, this feature would allow to rename a fence in Koji without breaking the export to RDM.

#195 would play nicely with this feature too.

**Comment by clburlison** [comment]
IMO the RDM implementation with Koji always had a little jank due to how the RDM base was built. I'd tag RDM support as depreciated and allow Turtle to drop it completely in 2024. Only have so many hours in the day.

I always just copy/pasted my Koji routes into RDM.

**Comment by DrMurx** [comment]
@clburlison Given that RDM will be phased out anyway, I'll just close this issue.
