### ISSUE TITLE
Don't calculate Pokestops, Gyms and Spawnpoints for larger areas automatically.

### ISSUE THREAD

**Issue by Cronick** [TurtIeSocks/Koji#197]
As for someone that has decided to scan my home-country fully for routes.

When your polygons get over a certain size and complexity. It just takes forever to calculate the values for Pokestops, Gyms & Spawnpoints in the polygons, and puts the database up for a task that it's not happy about 😄 

My suggestion would be to implement some sort of sweetspot by area size, or just a simple settings option to don't calculate these automatically when clicking on a polygon.

So instead you can click on an icon to get the values, instead of pushing a task to the database everytime you click on a polygon.

![image](https://github.com/TurtIeSocks/Koji/assets/5100210/1262a982-dad2-431f-911c-155bd4c88062) ![image](https://github.com/TurtIeSocks/Koji/assets/5100210/9f224336-0c91-4b55-8e4e-222683e960bc)

**Comment by TurtIeSocks** [comment]
I suspect that if we only add this limitation to spawnpoints then the other 2 queries will be fast enough that it shouldn't matter. (I believe it's a promise.all so the other 2 are likely always waiting for spawnpoints.)

**Comment by lenisko** [comment]
I think I shared this idea, but possible only within my mind.... 😶

I saw it like a value field with sane default, if area is lower than X km2 pull the data automatically. Otherwise, add a button like mentioned in post above.
