### ISSUE TITLE
RDM + Golbat Hybrid use case

### ISSUE THREAD

**Issue by notheowner** [TurtIeSocks/Koji#199]
People are switching data processing from RDM to Golbat in a Hybrid setup. 
This currently results in a situation where you need 2 databases for Koji, one for the Spawnpoints(in the Golbat database) and one for the Scanner instances(in the RDM database). So you'd want the Golbat spawnpoints for route creation, but you can not update your instances to the scanner through Koji or pull them from the scanner to Koji directly. 

Maybe an option through config to load instances or other data in the scanner database in Koji and still use Golbat for spawnpoints/pokestops etc.

**Comment by klablabla** [comment]
That would be a great addition to Koji. 
Also have RDM and Golbat running.
