### ISSUE TITLE
Unable to save route descriptions

### ISSUE THREAD

**Issue by SenorKarlos** [TurtIeSocks/Koji#202]
Saving fails with no error per the images attached
![image](https://github.com/TurtIeSocks/Koji/assets/10344114/35833a24-f7d2-49fb-a3c0-875cacc6ae32)
![image](https://github.com/TurtIeSocks/Koji/assets/10344114/e11c9ffe-e96e-4db0-921e-e1f8aece5fc7)
![image](https://github.com/TurtIeSocks/Koji/assets/10344114/6b993a80-9acd-4b43-b716-338522061236)

**Comment by clburlison** [comment]
Confirmed on my end. Low priority either way.

**Comment by TurtIeSocks** [comment]
Resolved in https://github.com/TurtIeSocks/Koji/commit/c69cc3c59481fe0f259ec7079a735af71c886c4c
