### ISSUE TITLE
Stats logging may break clustering

### ISSUE THREAD

**Issue by DrMurx** [TurtIeSocks/Koji#222]
If the name of the area is too long, the stats output in [server/algorithms/src/stats.rs#L77](https://github.com/TurtIeSocks/Koji/blob/094bb7da4d10181d01954137ee427af89bb86481/server/algorithms/src/stats.rs#L77) throws an exception due to an integer underflow, and kills returning the clustering results.

**Comment by TurtIeSocks** [comment]
...how long of a name are we talking here?

**Comment by DrMurx** [comment]
I guess it's something in the range of 55 characters? The problem is that `WIDTH[..(WIDTH.len() - text.len())]` at
 [server/algorithms/src/stats.rs#L66](https://github.com/TurtIeSocks/Koji/blob/094bb7da4d10181d01954137ee427af89bb86481/server/algorithms/src/stats.rs#L66) will underflow if `text.len()` is greater than `WIDTH.len()`. Since it's a unsigned 64 bit value, it causes an index out of bounds panic at 2^64.
