### ISSUE TITLE
Missing points on cluster

### ISSUE THREAD

**Issue by lenisko** [TurtIeSocks/Koji#90]
Points are missed on clustering. Same thing on routing.

![2023-03-04_14-31-01-firefox](https://user-images.githubusercontent.com/10072920/222904640-f03ef804-d35b-447b-af1e-9da2452f0b88.png)
![2023-03-04_14-30-57-firefox](https://user-images.githubusercontent.com/10072920/222904643-b369b177-8c29-4e6b-a69f-a28e477d471c.png)
![2023-03-04_14-31-11-firefox](https://user-images.githubusercontent.com/10072920/222904644-3eed7cdf-91f0-40b9-a7aa-c049e868db70.png)
![2023-03-04_14-31-32-firefox](https://user-images.githubusercontent.com/10072920/222904645-449947cc-7d1b-4690-8bd7-72b30b17b5de.png)

**Comment by TurtIeSocks** [comment]
Resolved in #200
